#index:
#    path: /
#    controller: App\Controller\DefaultController::index

admin_search:
    path: /search
    controller: App\Controller\GestionUserController::admin
    methods: ['GET', 'POST'] 