#index:
#    path: /
#    controller: App\Controller\DefaultController::index
search_events:
  path: /search
  controller: App\Controller\EvenementController::search

ajax_search:
  path: /search
  controller: App\Controller\statutController::search
